### ISSUE TITLE
Transitive dependency on `lens` via `these`

### ISSUE THREAD

**Issue by jkachmar** [nikita-volkov/refined#38]
#17 (and version 0.3 in the changelog) states that `these` was to be dropped because it's a heavy dependency.

However, it looks like it's still in the `.cabal` file, andbuilding `refined-0.4.1` on my machine still pulls `lens` down.

**Comment by chessai** [comment]
`these` was re-added, because I wanted to avoid code duplication, but `refined`'s use of the `These` datatype is so light that I'm reconsidering dropping it.

Additionally, I'm not sure i want dependencies of `aeson` or `QuickCheck` either - i'd rather have `quickcheck-refined` and `aeson-refined` as libraries.

I'm +1 on making this change. If anyone has a PR, that would be appreciated. If not, I'll get to it soon.

**Comment by jkachmar** [comment]
Opened #39, which simply re-adds `Refined.These`. 

I'm nominally unaffected by QuickCheck and Aeson stuff, and don't have a strong opinion on separate libraries versus flags. 

Is there any reason to prefer one over the other (aside from avoiding the hassle of CPP)?

**Comment by symbiont-joseph-kachmar** [comment]
Thanks for merging my PR! Is there anything else I can do to help get a new release out the door?

**Comment by chessai** [comment]
Eh, I actually think I'm fine with having QuickCheck / Aeson behind flags.

**Comment by chessai** [comment]
@symbiont-joseph-kachmar i can make a new release right now. thanks for reminding me.

**Comment by chessai** [comment]
delayed because of a bunch of changes. added doctests for all predicates, added three new predicates (Even, Odd, DivisibleBy), and made all constructors unary instead of nullary. the version that does not transitively depend on lens has been uploaded to hackage as version 0.4.2.
