### ISSUE TITLE
Feature request: unsafeRefine

### ISSUE THREAD

**Issue by fosskers** [nikita-volkov/refined#7]
I have the following:
```haskell
class Group a where
  ...
  -- | Each elements of /a/ must possess an inverse.
  inverse :: a -> a
  ...

type Pos = Refined (GreaterThan 0) (Ratio Word)

instance Group Pos where
  ...
  inverse n = fromRight undefined . refined . recip $ unrefine n
  ...
```
By virtue of being accepted into `inverse`, we know that `n` already satisfies the `Refined` predicate. We also know from the nature of `Ratio` that `recip` *cannot* fail here, nor yield a resulting value outside of the predicate's range.

Proposal: Some dark, evil `unsafeRefine` (or the `Refined` constructor itself) that injects my value back into the `Refined` newtype without checking the condition. In the case of `inverse` here, we know the `refined` check will always succeed, so there's no need to check it.

Thoughts?

**Comment by nikita-volkov** [comment]
What about `unsafeCoerce`?

**Comment by fosskers** [comment]
Yup, seems to work. Thanks.

**Comment by chessai** [comment]
I'm glad I came across this issue, because I wanted to address it somewhere.
I think I will address it in the README, but for now:

The point of this library is to allow construction of a `Refined` value only with supplied functions, and never the constructor itself. As such, it would be unsafe to expose the `Refined` constructor to the end user. If a user really needs to grab the value out of a `Refined`, they should use `unsafeCoerce` judiciously.
